# This is a github action to check if a build can be done.

name: check-build

on:
  pull_request:

jobs:
  make-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3

      - name: action
        run: ls

